<?php

/**
 * PluginmyContentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmyContentTable extends myBaseTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmyContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmyContent');
    }

    /**
     * Запрос по текущему домену
     *
     * @param Doctrine_Query $q
     * @return Doctrine_Query
     */
    public function queryByDomain(Doctrine_Query $q = null)
    {
        $domain = sfContext::getInstance()->getRequest()->getHost();

        if (is_null($q)) {
            $q = $this->createQuery('a');
        }

        $alias = $q->getRootAlias();

        return $q->withI18n($alias)
            ->addWhere(sprintf('(%1$s.domain = ? OR %1$s.domain = ?)', $alias), array($domain, '*'))
            ->orderBy($alias . '.domain DESC');
    }

    /**
     * Выборка по текущему домену
     *
     * @param Doctrine_Query $q
     * @return Doctrine_Collection
     */
    public function getByDomain(Doctrine_Query $q = null)
    {
        return $this->queryByDomain($q)->execute();
    }

    /**
     * Запрос по блоку
     *
     * @param Doctrine_Query $q
     * @return Doctrine_Query
     */
    public function queryByBlock($block, Doctrine_Query $q = null)
    {
        if (is_null($q)) {
            $q = $this->createQuery('a');
        }

        return $this->queryByDomain($q)
            ->andWhere($q->getRootAlias() . '.block = ?', $block);
    }

    /**
     * Выборка по блоку
     *
     * @param Doctrine_Query $q
     * @return Doctrine_Collection
     */
    public function getByBlock($block, Doctrine_Query $q = null)
    {
        return $this->queryByBlock($block, $q)->execute();
    }
}