#dev:
#  .settings:
#    domains:
#      - *
#      - crimea.dev
#      - eastbooking.dev
#
#all:
#    domains:
#      - *
#      - eastbooking.ru
#      - eastbooking.com
#      - eastbooking.com.ua
