#myContentAdmin:
#  class: sfDoctrineRouteCollection
#  options:
#    model:                myContent
#    module:               myContentAdmin
#    prefix_path:          /myContentAdmin
#    column:               id
#    with_wildcard_routes: true


#myContent:
#  url: /page/:url
#  class: sfDoctrineRoute
#  options: { model: myContent, type: object, method_for_query: getByDomain }
#  params: { module: myContent, action: show }
#  requirements:
#    sf_method: get